/**
 * Skill Map + Curriculum Core — representative skill catalog (Phase 1).
 *
 * A modest but useful catalog across the six domains. It intentionally does
 * NOT model the whole English language: it is a deterministic, extensible
 * backbone that later phases can grow.
 *
 * Pure data. No persistence, no scores.
 */

import type { PracticeMode, SkillEvidenceSource, SkillNode } from './types';

/** Convenience factory keeping catalog literals readable and checked. */
function skill(
  id: string,
  domain: SkillNode['domain'],
  title: string,
  description: string,
  prerequisites: readonly string[],
  relatedSkills: readonly string[],
  evidenceSources: readonly SkillEvidenceSource[],
  recommendedPracticeTypes: readonly PracticeMode[],
): SkillNode {
  return {
    id,
    domain,
    title,
    description,
    prerequisites,
    relatedSkills,
    evidenceSources,
    recommendedPracticeTypes,
  };
}

const SPOKEN_EVIDENCE: readonly SkillEvidenceSource[] = [
  'conversation',
  'deep_speaking',
  'adaptive_lesson',
];

/** Ordered skill catalog. Ids are stable, unique, and human-readable. */
export const SKILL_CATALOG: readonly SkillNode[] = [
  // ---------------------------------------------------------------- grammar
  skill(
    'sentence_structure',
    'grammar',
    'Sentence structure',
    'Build a complete, well-formed English sentence with a subject and verb.',
    [],
    ['present_tense', 'articles'],
    ['conversation', 'adaptive_lesson'],
    ['guided_dialogue', 'drill'],
  ),
  skill(
    'present_tense',
    'grammar',
    'Present tense',
    'Express present states and routines accurately.',
    ['sentence_structure'],
    ['past_tense', 'future_forms'],
    ['conversation', 'adaptive_lesson'],
    ['guided_dialogue', 'drill'],
  ),
  skill(
    'past_tense',
    'grammar',
    'Past tense',
    'Talk about completed past events with correct forms.',
    ['sentence_structure', 'present_tense'],
    ['future_forms', 'relative_clauses'],
    SPOKEN_EVIDENCE,
    ['guided_dialogue', 'drill'],
  ),
  skill(
    'future_forms',
    'grammar',
    'Future forms',
    'Express plans, intentions, and predictions about the future.',
    ['present_tense'],
    ['conditionals'],
    ['conversation', 'adaptive_lesson'],
    ['guided_dialogue', 'drill'],
  ),
  skill(
    'articles',
    'grammar',
    'Articles',
    'Use a, an, the, and the zero article appropriately.',
    ['sentence_structure'],
    ['prepositions'],
    ['conversation', 'adaptive_lesson'],
    ['drill', 'guided_dialogue'],
  ),
  skill(
    'prepositions',
    'grammar',
    'Prepositions',
    'Choose correct prepositions of time, place, and movement.',
    ['sentence_structure', 'articles'],
    ['collocations'],
    ['conversation', 'adaptive_lesson'],
    ['drill', 'guided_dialogue'],
  ),
  skill(
    'conditionals',
    'grammar',
    'Conditionals',
    'Express real and hypothetical conditions with correct structure.',
    ['present_tense', 'future_forms'],
    ['relative_clauses'],
    SPOKEN_EVIDENCE,
    ['guided_dialogue', 'role_play'],
  ),
  skill(
    'relative_clauses',
    'grammar',
    'Relative clauses',
    'Add descriptive detail with who, which, that, and where.',
    ['sentence_structure', 'past_tense'],
    ['elaboration'],
    ['conversation', 'adaptive_lesson'],
    ['guided_dialogue', 'drill'],
  ),

  // ------------------------------------------------------------- vocabulary
  skill(
    'core_vocabulary',
    'vocabulary',
    'Core vocabulary',
    'High-frequency words for everyday and professional communication.',
    [],
    ['contextual_meaning', 'collocations'],
    ['vocabulary', 'review', 'conversation'],
    ['review', 'guided_dialogue'],
  ),
  skill(
    'contextual_meaning',
    'vocabulary',
    'Contextual meaning',
    'Work out and use word meaning from context.',
    ['core_vocabulary'],
    ['collocations', 'inference_listening'],
    ['vocabulary', 'review', 'conversation'],
    ['review', 'guided_dialogue'],
  ),
  skill(
    'collocations',
    'vocabulary',
    'Collocations',
    'Use natural word combinations rather than literal translations.',
    ['core_vocabulary'],
    ['common_expressions', 'word_families'],
    ['vocabulary', 'review', 'conversation'],
    ['review', 'guided_dialogue'],
  ),
  skill(
    'word_families',
    'vocabulary',
    'Word families',
    'Move between related word forms (decide, decision, decisive).',
    ['core_vocabulary'],
    ['collocations'],
    ['vocabulary', 'review'],
    ['review', 'drill'],
  ),

  // ------------------------------------------------------------ expressions
  skill(
    'common_expressions',
    'expressions',
    'Common expressions',
    'Everyday fixed expressions used in natural conversation.',
    ['core_vocabulary'],
    ['phrasal_verbs', 'functional_language'],
    SPOKEN_EVIDENCE,
    ['guided_dialogue', 'role_play'],
  ),
  skill(
    'phrasal_verbs',
    'expressions',
    'Phrasal verbs',
    'Understand and use common multi-word verbs.',
    ['common_expressions', 'collocations'],
    ['functional_language'],
    ['conversation', 'adaptive_lesson', 'review'],
    ['guided_dialogue', 'drill'],
  ),
  skill(
    'functional_language',
    'expressions',
    'Functional language',
    'Agreeing, disagreeing, requesting, and suggesting with natural phrasing.',
    ['common_expressions'],
    ['professional_expressions', 'opinion_and_reasoning'],
    SPOKEN_EVIDENCE,
    ['role_play', 'guided_dialogue'],
  ),
  skill(
    'professional_expressions',
    'expressions',
    'Professional expressions',
    'Register-appropriate expressions for the workplace.',
    ['functional_language', 'core_vocabulary'],
    ['explanation'],
    SPOKEN_EVIDENCE,
    ['role_play', 'free_speaking'],
  ),

  // ---------------------------------------------------------------- speaking
  skill(
    'fluency',
    'speaking',
    'Fluency',
    'Sustain speech with fewer long pauses and restarts.',
    ['sentence_structure'],
    ['elaboration', 'reformulation'],
    SPOKEN_EVIDENCE,
    ['free_speaking', 'guided_dialogue'],
  ),
  skill(
    'elaboration',
    'speaking',
    'Elaboration',
    'Extend answers with reasons, details, and examples.',
    ['fluency', 'relative_clauses'],
    ['explanation', 'opinion_and_reasoning'],
    SPOKEN_EVIDENCE,
    ['free_speaking', 'role_play'],
  ),
  skill(
    'follow_up_questions',
    'speaking',
    'Follow-up questions',
    'Keep a conversation going by asking relevant follow-up questions.',
    ['fluency'],
    ['opinion_and_reasoning'],
    SPOKEN_EVIDENCE,
    ['role_play', 'guided_dialogue'],
  ),
  skill(
    'opinion_and_reasoning',
    'speaking',
    'Opinion and reasoning',
    'State a view and support it with clear reasoning.',
    ['elaboration', 'functional_language'],
    ['explanation', 'problem_solving'],
    SPOKEN_EVIDENCE,
    ['free_speaking', 'role_play'],
  ),
  skill(
    'explanation',
    'speaking',
    'Explanation',
    'Explain an idea, process, or problem so a listener can follow it.',
    ['elaboration'],
    ['problem_solving', 'technical_terms'],
    SPOKEN_EVIDENCE,
    ['free_speaking', 'role_play'],
  ),
  skill(
    'problem_solving',
    'speaking',
    'Problem solving',
    'Talk through a problem, options, and a resolution aloud.',
    ['explanation', 'opinion_and_reasoning'],
    ['reformulation'],
    SPOKEN_EVIDENCE,
    ['role_play', 'free_speaking'],
  ),
  skill(
    'reformulation',
    'speaking',
    'Reformulation',
    'Rephrase your own message when you are not understood.',
    ['fluency'],
    ['problem_solving'],
    SPOKEN_EVIDENCE,
    ['free_speaking', 'guided_dialogue'],
  ),

  // --------------------------------------------------------------- listening
  skill(
    'gist_listening',
    'listening',
    'Listening for gist',
    'Catch the main idea of a passage without every detail.',
    [],
    ['detail_listening', 'inference_listening'],
    ['listening', 'adaptive_lesson'],
    ['listening_task'],
  ),
  skill(
    'detail_listening',
    'listening',
    'Listening for detail',
    'Catch specific facts, numbers, and names in speech.',
    ['gist_listening'],
    ['connected_speech_awareness'],
    ['listening', 'adaptive_lesson'],
    ['listening_task'],
  ),
  skill(
    'inference_listening',
    'listening',
    'Listening for inference',
    'Understand what is implied but not stated.',
    ['gist_listening', 'detail_listening'],
    ['contextual_meaning'],
    ['listening'],
    ['listening_task'],
  ),
  skill(
    'connected_speech_awareness',
    'listening',
    'Connected speech awareness',
    'Hear how words link, reduce, and blend in natural speech.',
    ['detail_listening'],
    ['word_stress', 'rhythm'],
    ['listening', 'pronunciation'],
    ['listening_task', 'shadowing'],
  ),

  // ----------------------------------------------------------- pronunciation
  skill(
    'sound_clarity',
    'pronunciation',
    'Sound clarity',
    'Produce individual sounds clearly enough to be understood.',
    [],
    ['word_stress', 'intelligibility'],
    ['pronunciation', 'deep_speaking'],
    ['shadowing', 'reading_aloud'],
  ),
  skill(
    'word_stress',
    'pronunciation',
    'Word stress',
    'Place stress on the correct syllable in words.',
    ['sound_clarity'],
    ['sentence_stress', 'rhythm'],
    ['pronunciation', 'listening'],
    ['shadowing', 'reading_aloud'],
  ),
  skill(
    'sentence_stress',
    'pronunciation',
    'Sentence stress',
    'Stress the right words to carry meaning in a sentence.',
    ['word_stress'],
    ['rhythm', 'intelligibility'],
    ['pronunciation', 'deep_speaking'],
    ['shadowing', 'reading_aloud'],
  ),
  skill(
    'rhythm',
    'pronunciation',
    'Rhythm',
    'Keep a natural English rhythm rather than a syllable-timed one.',
    ['word_stress', 'sentence_stress'],
    ['intelligibility'],
    ['pronunciation', 'deep_speaking'],
    ['shadowing', 'reading_aloud'],
  ),
  skill(
    'intelligibility',
    'pronunciation',
    'Intelligibility',
    'Be reliably understood by listeners in real conversation.',
    ['sound_clarity', 'sentence_stress'],
    ['fluency'],
    ['pronunciation', 'conversation', 'deep_speaking'],
    ['free_speaking', 'reading_aloud'],
  ),
];

/** Look up a skill node by id. */
export function getSkill(id: string): SkillNode | undefined {
  return SKILL_CATALOG.find((node) => node.id === id);
}
